version: 2.1

jobs:
  build:
    docker:
      - image: docker:27.2.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 27.2.0
      - run:
          name: Build Docker image
          command: docker build -t web-ci .
      - run:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag web-ci davodev35/web-ci:latest
            docker push davodev35/web-ci:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
